### ISSUE TITLE
Lesson will not open. 

### ISSUE THREAD

**Issue by carl1984r** [learn-co-curriculum/jsdom-toy-tale#3]
// ♥ learn open jsdom-toy-tale-online-web-sp-000
Looking for lesson...
Traceback (most recent call last):
        11: from /usr/local/rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in `<main>'
        10: from /usr/local/rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in `eval'
         9: from /usr/local/rvm/gems/ruby-2.6.1/bin/learn-open:23:in `<main>'
         8: from /usr/local/rvm/gems/ruby-2.6.1/bin/learn-open:23:in `load'
         7: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-open-1.2.28/bin/learn-open:7:in `<to
p (required)>'
         6: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-open-1.2.28/lib/learn_open/opener.rb
:12:in `run'
         5: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-open-1.2.28/lib/learn_open/opener.rb
:38:in `run'
         4: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-open-1.2.28/lib/learn_open/lessons.r
b:19:in `classify'
         3: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-open-1.2.28/lib/learn_open/lessons.r
b:19:in `find'
         2: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-open-1.2.28/lib/learn_open/lessons.r
b:19:in `each'
         1: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-open-1.2.28/lib/learn_open/lessons.r
b:20:in `block in classify'
/usr/local/rvm/gems/ruby-2.6.1/gems/learn-open-1.2.28/lib/learn_open/lessons/ios_lesson.rb:6:in
 `detect': undefined method `any?' for false:FalseClass (NoMethodError)

**Comment by rrcobb** [comment]
Thanks for reporting! Should be fixed by e3cd69d
