### ISSUE TITLE
json-server unable to load index.html, index.css, or index.js

### ISSUE THREAD

**Issue by IgoVeyner** [learn-co-curriculum/jsdom-toy-tale#7]
Not sure if there was a change to json-server since this lab was written but for these to work they must be nested inside a folder at the root directory named "public". Currently they are not and the index is the default json-server index.

**Comment by lizbur10** [comment]
Hi @IgoVeyner ! I'm sorry to hear you ran into a problem with this. I'm having difficulty reproducing the issue, so I'm going to close it for now.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment, I'd be happy to take a second look!

As always, thanks for contributing! 💙
